pipeline {
    agent any

    stages {
        stage('Source') {
            steps {
                git 'https://github.com/delfinalber/entornos-integracion-actividad-3.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building stage!'
                dir('unir-cicd-master') {
                    sh 'make build'
                }
            }
        }
        stage('Unit tests') {
            steps {
                dir('unir-cicd-master') {
                    sh 'make test-unit'
                    sh 'test -f results/unit_result.xml'
                }
                archiveArtifacts artifacts: 'unir-cicd-master/results/*.xml', allowEmptyArchive: false
            }
        }
        stage('API tests') {
            steps {
                dir('unir-cicd-master') {
                    sh 'make test-api'
                    sh 'test -f results/api_result.xml'
                }
                archiveArtifacts artifacts: 'unir-cicd-master/results/api_result.xml', allowEmptyArchive: false
            }
        }
        stage('E2E tests') {
            steps {
                dir('unir-cicd-master') {
                    sh 'make test-e2e'
                    sh 'test -f results/cypress_result.xml'
                }
                archiveArtifacts artifacts: 'unir-cicd-master/results/cypress_result.xml', allowEmptyArchive: false
            }
        }
    }
    post {
        always {
            junit 'unir-cicd-master/results/*_result.xml'
            cleanWs()
        }
        failure {
            mail to: 'delfinalber@gmail.com',
                 subject: "Pipeline FALLIDO: ${currentBuild.fullDisplayName}",
                 body: "El pipeline ha fallado.\n\nProyecto: ${env.JOB_NAME}\nBuild: ${env.BUILD_NUMBER}\nURL: ${env.BUILD_URL}"
        }
    }
}
